#index:
#    path: / lien de la vue
#    controller: App\Controller\DefaultController::index le controller qui lui est associé
personne_index:
  path: /personne
  controller: App\Controller\PersonneController::index


personne_add:
  path: /personne/form_view/
  controller: App\Controller\PersonneController::AddOrUpdate

personne_update:
  path: /personne/form_view/{Nom}/{Prenom}
  controller: App\Controller\PersonneController::AddOrUpdate
  requirements:
    nom: \w+
    prenom: \w+

personne_delete:
  path: /personne/{id}/delete
  methods: [GET, POST]
  controller: App\Controller\PersonneController::delete

